# Generated by Django 3.0.7 on 2020-06-04 03:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombreCliente', models.CharField(max_length=100)),
                ('nitCliente', models.CharField(max_length=15)),
                ('direccionCliente', models.CharField(max_length=200)),
                ('telefonoCliente', models.CharField(max_length=15)),
                ('correoCliente', models.EmailField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Personal',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombrePersonal', models.CharField(max_length=100)),
                ('nitPersonal', models.CharField(max_length=15)),
                ('direccionPersonal', models.CharField(max_length=200)),
                ('telefonoPersonal', models.CharField(max_length=15)),
                ('correoPersonal', models.EmailField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Productos',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombreProducto', models.CharField(max_length=100)),
                ('proveedorProducto', models.CharField(max_length=120)),
                ('fechaProducto', models.FloatField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Proveedor',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombreProveedor', models.CharField(max_length=100)),
                ('nitProveedor', models.CharField(max_length=15)),
                ('direccionProveedor', models.CharField(max_length=200)),
                ('telefonoProveedor', models.CharField(max_length=15)),
                ('correoProveedor', models.EmailField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Vehiculo',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('marcaVehiculo', models.CharField(max_length=100)),
                ('modeloVehiculo', models.CharField(max_length=100)),
                ('placaVehiculo', models.CharField(max_length=10)),
                ('personalVehiculo', models.CharField(max_length=100)),
            ],
        ),
    ]
